version: '3.5'

services:
  consul:
    container_name: service.framework-test.consul
    image: consul:latest
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600/udp
    volumes:
      - .service-resources/dev/consul:/etc/consul.d
    command: "agent -config-dir=/etc/consul.d -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -ui"

  registrator:
    container_name: service.framework-test.registrator
    image: gliderlabs/registrator:latest
    command: consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  cache:
    container_name: service.framework-test.redis-cache
    image: redis:latest
    ports:
      - 10755:3000
    networks:
      - service-overlay
    depends_on:
      - registrator

  mysql:
    container_name: service.framework-test.mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /app
    volumes:
      - ./storage/data/mysql:/app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=service-framework-test
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    ports:
      - 44008:3306
    networks:
      - service-overlay
    depends_on:
      - registrator

  application:
    container_name: service.framework-test.application
    build: .
    volumes:
      - .:/app:cached
    networks:
      - service-overlay
    depends_on:
      - cache
      - mysql

  scheduler:
    container_name: service.framework-test.scheduler
    build: .
    environment:
      CONTAINER_ROLE: scheduler
    volumes:
      - .:/app:cached
    networks:
      - service-overlay
    depends_on:
      - application

  webserver:
    container_name: service.framework-test.webserver
    build: .service-resources/dev/nginx
    working_dir: /app
    volumes:
      - .:/app
      - ./.service-resources/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 13833:80
    networks:
      - service-overlay
    depends_on:
      - application

networks:
  service-overlay:
    external:
      name: service-overlay
