version: '3.5'

services:
  mysql:
    container_name: service.framework-test.mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /app
    volumes:
      - mysql-volume:/app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=service-framework-test
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    ports:
      - 44008:3306
    networks:
      - service-overlay

  webserver:
    container_name: service.framework-test.webserver
    build: .service-resources/dev/nginx
    working_dir: /app
    volumes:
      - .:/app
      - ./.service-resources/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 13833:80
    networks:
      - service-overlay

  application:
    container_name: service.framework-test.application
    build: .
    volumes:
      - .:/app:cached
    networks:
      - service-overlay

  scheduler:
    container_name: service.framework-test.scheduler
    build: .
    environment:
      CONTAINER_ROLE: scheduler
    volumes:
      - .:/app:cached
    networks:
      - service-overlay

networks:
  service-overlay:
    external:
      name: service-overlay

volumes:
  mysql-volume:
    driver: local
