<?php

// Asset routes...
Route::get('/assets', 'Api\Asset\GetAssetsController')->name('get-assets');

// Page routes...
Route::get('/pages', 'Api\Page\GetPagesController')->name('get-pages');

// Collection routes...
Route::get('/collections', 'Api\Collection\GetCollectionsController')->name('get-collections');

// Form routes...
Route::get('/forms', 'Api\Form\GetFormsController')->name('get-forms');

// Email routes...
Route::get('/emails', 'Api\Email\GetEmailsController')->name('get-emails');

// Profile routes...
Route::get('/profiles', 'Api\Profile\GetProfilesController')->name('get-profiles');

// Automation routes...
Route::get('/automations', 'Api\Automation\GetAutomationsController')->name('get-automations');

// Domain routes...
Route::get('/domains', 'Api\Domain\GetDomainsController')->name('get-domains');

// Workflow routes...
Route::get('/workflows', 'Api\Workflow\GetWorkflowsController')->name('get-workflows');

// Setting routes...
Route::get('/settings', 'Api\Setting\GetSettingsController')->name('get-settings');
