- name: Swarm init
  command: docker swarm init --advertise-addr {{ inventory_hostname }}

- name: Get worker token
  command: docker swarm join-token worker -q
  register: worker_token

- name: Show worker token
  debug: var=worker_token.stdout

- name: Get manager token
  command: docker swarm join-token manager -q
  register: manager_token

- name: Show manager token
  debug: var=manager_token.stdout
